# ==========================================
# \uD83E\uDDEA AMBIENTE DE TESTES RAPIDOS (BANCO H2)
# ==========================================
spring.datasource.url=jdbc:h2:mem:impactdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# O 'create-drop' apaga tudo e recria do zero toda vez
spring.jpa.hibernate.ddl-auto=create-drop
spring.h2.console.enabled=true