# ==========================================
# CONFIGURAÇÕES DE BANCO DE DADOS (HÍBRIDO: NUVEM E LOCAL)
# ==========================================
# O Java tenta usar as variáveis do Render. Se não achar (no seu PC), ele usa o localhost.
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/impact_logistica}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASS:0000}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# ==========================================
# CONFIGURAÇÕES DE VISUALIZAÇÃO E ARQUIVOS
# ==========================================
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Permite ao Spring ler as imagens carregadas sem precisar de reiniciar o servidor
spring.web.resources.static-locations=classpath:/static/,file:uploads/

# ==========================================
# SEGURANÇA E INTEGRAÇÕES
# ==========================================
# Credenciais padrão do Spring Security
spring.security.user.name=admin
spring.security.user.password=123456

# Chave de Acesso da IA (Gemini)
gemini.api.key= SUA_CHAVE_API_GEMINI

# ==========================================
# PORTA DO SERVIDOR
# ==========================================
# O Render injeta a porta dinamicamente, mas no seu PC vai rodar na 8080
server.port=${PORT:8080}
